
// This file is generated by blook
// Neither touch/modify nor include this file in your project!

#include "Windows.h"

// blook: USE_STATIC_INITIALIZATION_TO_INIT_EXPORTS
void (*blookHijackFuncs[47])() = {};
const char* blookHijackFuncNames[] = {
 "HidD_FlushQueue",
 "HidD_FreePreparsedData",
 "HidD_GetAttributes",
 "HidD_GetConfiguration",
 "HidD_GetFeature",
 "HidD_GetHidGuid",
 "HidD_GetIndexedString",
 "HidD_GetInputReport",
 "HidD_GetManufacturerString",
 "HidD_GetMsGenreDescriptor",
 "HidD_GetNumInputBuffers",
 "HidD_GetPhysicalDescriptor",
 "HidD_GetPreparsedData",
 "HidD_GetProductString",
 "HidD_GetSerialNumberString",
 "HidD_Hello",
 "HidD_SetConfiguration",
 "HidD_SetFeature",
 "HidD_SetNumInputBuffers",
 "HidD_SetOutputReport",
 "HidP_GetButtonArray",
 "HidP_GetButtonCaps",
 "HidP_GetCaps",
 "HidP_GetData",
 "HidP_GetExtendedAttributes",
 "HidP_GetLinkCollectionNodes",
 "HidP_GetScaledUsageValue",
 "HidP_GetSpecificButtonCaps",
 "HidP_GetSpecificValueCaps",
 "HidP_GetUsageValue",
 "HidP_GetUsageValueArray",
 "HidP_GetUsages",
 "HidP_GetUsagesEx",
 "HidP_GetValueCaps",
 "HidP_GetVersionInternal",
 "HidP_InitializeReportForID",
 "HidP_MaxDataListLength",
 "HidP_MaxUsageListLength",
 "HidP_SetButtonArray",
 "HidP_SetData",
 "HidP_SetScaledUsageValue",
 "HidP_SetUsageValue",
 "HidP_SetUsageValueArray",
 "HidP_SetUsages",
 "HidP_TranslateUsagesToI8042ScanCodes",
 "HidP_UnsetUsages",
 "HidP_UsageListDifference",
};

int blookInit = ([] {
    char system_dir_path[MAX_PATH];
    GetSystemDirectoryA(system_dir_path, MAX_PATH);
    strcat_s(system_dir_path, "\\HID.dll");
    HMODULE lib = LoadLibraryA(system_dir_path);

    for (int i = 0; i < sizeof(blookHijackFuncs) / sizeof(blookHijackFuncs[0]); i++) {
        blookHijackFuncs[i] = (void (*)()) GetProcAddress(lib, blookHijackFuncNames[i]);
    }

    return 0;
})();

// blook: GENERATED_PLACEHOLDER_FUNCTION_EXPORTS
#pragma comment(linker, "/EXPORT:HidD_FlushQueue=BLOOK_PLACEHOLDER_1")
extern "C" void BLOOK_PLACEHOLDER_1() { return (blookHijackFuncs[0])(); }

#pragma comment(linker, "/EXPORT:HidD_FreePreparsedData=BLOOK_PLACEHOLDER_2")
extern "C" void BLOOK_PLACEHOLDER_2() { return (blookHijackFuncs[1])(); }

#pragma comment(linker, "/EXPORT:HidD_GetAttributes=BLOOK_PLACEHOLDER_3")
extern "C" void BLOOK_PLACEHOLDER_3() { return (blookHijackFuncs[2])(); }

#pragma comment(linker, "/EXPORT:HidD_GetConfiguration=BLOOK_PLACEHOLDER_4")
extern "C" void BLOOK_PLACEHOLDER_4() { return (blookHijackFuncs[3])(); }

#pragma comment(linker, "/EXPORT:HidD_GetFeature=BLOOK_PLACEHOLDER_5")
extern "C" void BLOOK_PLACEHOLDER_5() { return (blookHijackFuncs[4])(); }

#pragma comment(linker, "/EXPORT:HidD_GetHidGuid=BLOOK_PLACEHOLDER_6")
extern "C" void BLOOK_PLACEHOLDER_6() { return (blookHijackFuncs[5])(); }

#pragma comment(linker, "/EXPORT:HidD_GetIndexedString=BLOOK_PLACEHOLDER_7")
extern "C" void BLOOK_PLACEHOLDER_7() { return (blookHijackFuncs[6])(); }

#pragma comment(linker, "/EXPORT:HidD_GetInputReport=BLOOK_PLACEHOLDER_8")
extern "C" void BLOOK_PLACEHOLDER_8() { return (blookHijackFuncs[7])(); }

#pragma comment(linker, "/EXPORT:HidD_GetManufacturerString=BLOOK_PLACEHOLDER_9")
extern "C" void BLOOK_PLACEHOLDER_9() { return (blookHijackFuncs[8])(); }

#pragma comment(linker, "/EXPORT:HidD_GetMsGenreDescriptor=BLOOK_PLACEHOLDER_10")
extern "C" void BLOOK_PLACEHOLDER_10() { return (blookHijackFuncs[9])(); }

#pragma comment(linker, "/EXPORT:HidD_GetNumInputBuffers=BLOOK_PLACEHOLDER_11")
extern "C" void BLOOK_PLACEHOLDER_11() { return (blookHijackFuncs[10])(); }

#pragma comment(linker, "/EXPORT:HidD_GetPhysicalDescriptor=BLOOK_PLACEHOLDER_12")
extern "C" void BLOOK_PLACEHOLDER_12() { return (blookHijackFuncs[11])(); }

#pragma comment(linker, "/EXPORT:HidD_GetPreparsedData=BLOOK_PLACEHOLDER_13")
extern "C" void BLOOK_PLACEHOLDER_13() { return (blookHijackFuncs[12])(); }

#pragma comment(linker, "/EXPORT:HidD_GetProductString=BLOOK_PLACEHOLDER_14")
extern "C" void BLOOK_PLACEHOLDER_14() { return (blookHijackFuncs[13])(); }

#pragma comment(linker, "/EXPORT:HidD_GetSerialNumberString=BLOOK_PLACEHOLDER_15")
extern "C" void BLOOK_PLACEHOLDER_15() { return (blookHijackFuncs[14])(); }

#pragma comment(linker, "/EXPORT:HidD_Hello=BLOOK_PLACEHOLDER_16")
extern "C" void BLOOK_PLACEHOLDER_16() { return (blookHijackFuncs[15])(); }

#pragma comment(linker, "/EXPORT:HidD_SetConfiguration=BLOOK_PLACEHOLDER_17")
extern "C" void BLOOK_PLACEHOLDER_17() { return (blookHijackFuncs[16])(); }

#pragma comment(linker, "/EXPORT:HidD_SetFeature=BLOOK_PLACEHOLDER_18")
extern "C" void BLOOK_PLACEHOLDER_18() { return (blookHijackFuncs[17])(); }

#pragma comment(linker, "/EXPORT:HidD_SetNumInputBuffers=BLOOK_PLACEHOLDER_19")
extern "C" void BLOOK_PLACEHOLDER_19() { return (blookHijackFuncs[18])(); }

#pragma comment(linker, "/EXPORT:HidD_SetOutputReport=BLOOK_PLACEHOLDER_20")
extern "C" void BLOOK_PLACEHOLDER_20() { return (blookHijackFuncs[19])(); }

#pragma comment(linker, "/EXPORT:HidP_GetButtonArray=BLOOK_PLACEHOLDER_21")
extern "C" void BLOOK_PLACEHOLDER_21() { return (blookHijackFuncs[20])(); }

#pragma comment(linker, "/EXPORT:HidP_GetButtonCaps=BLOOK_PLACEHOLDER_22")
extern "C" void BLOOK_PLACEHOLDER_22() { return (blookHijackFuncs[21])(); }

#pragma comment(linker, "/EXPORT:HidP_GetCaps=BLOOK_PLACEHOLDER_23")
extern "C" void BLOOK_PLACEHOLDER_23() { return (blookHijackFuncs[22])(); }

#pragma comment(linker, "/EXPORT:HidP_GetData=BLOOK_PLACEHOLDER_24")
extern "C" void BLOOK_PLACEHOLDER_24() { return (blookHijackFuncs[23])(); }

#pragma comment(linker, "/EXPORT:HidP_GetExtendedAttributes=BLOOK_PLACEHOLDER_25")
extern "C" void BLOOK_PLACEHOLDER_25() { return (blookHijackFuncs[24])(); }

#pragma comment(linker, "/EXPORT:HidP_GetLinkCollectionNodes=BLOOK_PLACEHOLDER_26")
extern "C" void BLOOK_PLACEHOLDER_26() { return (blookHijackFuncs[25])(); }

#pragma comment(linker, "/EXPORT:HidP_GetScaledUsageValue=BLOOK_PLACEHOLDER_27")
extern "C" void BLOOK_PLACEHOLDER_27() { return (blookHijackFuncs[26])(); }

#pragma comment(linker, "/EXPORT:HidP_GetSpecificButtonCaps=BLOOK_PLACEHOLDER_28")
extern "C" void BLOOK_PLACEHOLDER_28() { return (blookHijackFuncs[27])(); }

#pragma comment(linker, "/EXPORT:HidP_GetSpecificValueCaps=BLOOK_PLACEHOLDER_29")
extern "C" void BLOOK_PLACEHOLDER_29() { return (blookHijackFuncs[28])(); }

#pragma comment(linker, "/EXPORT:HidP_GetUsageValue=BLOOK_PLACEHOLDER_30")
extern "C" void BLOOK_PLACEHOLDER_30() { return (blookHijackFuncs[29])(); }

#pragma comment(linker, "/EXPORT:HidP_GetUsageValueArray=BLOOK_PLACEHOLDER_31")
extern "C" void BLOOK_PLACEHOLDER_31() { return (blookHijackFuncs[30])(); }

#pragma comment(linker, "/EXPORT:HidP_GetUsages=BLOOK_PLACEHOLDER_32")
extern "C" void BLOOK_PLACEHOLDER_32() { return (blookHijackFuncs[31])(); }

#pragma comment(linker, "/EXPORT:HidP_GetUsagesEx=BLOOK_PLACEHOLDER_33")
extern "C" void BLOOK_PLACEHOLDER_33() { return (blookHijackFuncs[32])(); }

#pragma comment(linker, "/EXPORT:HidP_GetValueCaps=BLOOK_PLACEHOLDER_34")
extern "C" void BLOOK_PLACEHOLDER_34() { return (blookHijackFuncs[33])(); }

#pragma comment(linker, "/EXPORT:HidP_GetVersionInternal=BLOOK_PLACEHOLDER_35")
extern "C" void BLOOK_PLACEHOLDER_35() { return (blookHijackFuncs[34])(); }

#pragma comment(linker, "/EXPORT:HidP_InitializeReportForID=BLOOK_PLACEHOLDER_36")
extern "C" void BLOOK_PLACEHOLDER_36() { return (blookHijackFuncs[35])(); }

#pragma comment(linker, "/EXPORT:HidP_MaxDataListLength=BLOOK_PLACEHOLDER_37")
extern "C" void BLOOK_PLACEHOLDER_37() { return (blookHijackFuncs[36])(); }

#pragma comment(linker, "/EXPORT:HidP_MaxUsageListLength=BLOOK_PLACEHOLDER_38")
extern "C" void BLOOK_PLACEHOLDER_38() { return (blookHijackFuncs[37])(); }

#pragma comment(linker, "/EXPORT:HidP_SetButtonArray=BLOOK_PLACEHOLDER_39")
extern "C" void BLOOK_PLACEHOLDER_39() { return (blookHijackFuncs[38])(); }

#pragma comment(linker, "/EXPORT:HidP_SetData=BLOOK_PLACEHOLDER_40")
extern "C" void BLOOK_PLACEHOLDER_40() { return (blookHijackFuncs[39])(); }

#pragma comment(linker, "/EXPORT:HidP_SetScaledUsageValue=BLOOK_PLACEHOLDER_41")
extern "C" void BLOOK_PLACEHOLDER_41() { return (blookHijackFuncs[40])(); }

#pragma comment(linker, "/EXPORT:HidP_SetUsageValue=BLOOK_PLACEHOLDER_42")
extern "C" void BLOOK_PLACEHOLDER_42() { return (blookHijackFuncs[41])(); }

#pragma comment(linker, "/EXPORT:HidP_SetUsageValueArray=BLOOK_PLACEHOLDER_43")
extern "C" void BLOOK_PLACEHOLDER_43() { return (blookHijackFuncs[42])(); }

#pragma comment(linker, "/EXPORT:HidP_SetUsages=BLOOK_PLACEHOLDER_44")
extern "C" void BLOOK_PLACEHOLDER_44() { return (blookHijackFuncs[43])(); }

#pragma comment(linker, "/EXPORT:HidP_TranslateUsagesToI8042ScanCodes=BLOOK_PLACEHOLDER_45")
extern "C" void BLOOK_PLACEHOLDER_45() { return (blookHijackFuncs[44])(); }

#pragma comment(linker, "/EXPORT:HidP_UnsetUsages=BLOOK_PLACEHOLDER_46")
extern "C" void BLOOK_PLACEHOLDER_46() { return (blookHijackFuncs[45])(); }

#pragma comment(linker, "/EXPORT:HidP_UsageListDifference=BLOOK_PLACEHOLDER_47")
extern "C" void BLOOK_PLACEHOLDER_47() { return (blookHijackFuncs[46])(); }
